#!/usr/bin/perl -w

use strict;
use warnings;

use CGI::Carp qw/fatalsToBrowser/;
use CGI qw/standard/;
use CGI::Session;
use Data::Dumper;
use Auth;

my $cgi = CGI->new;
my $session = CGI::Session->new($cgi);

if( defined $session->param('logged_in') && 
    $session->param('logged_in') == 1) {
    
    print $cgi->redirect(-URL =>'http://' . $ENV{SERVER_NAME} . '/cgi-bin/home');
}

print $cgi->header;

print <<'QED';
<!DOCTYPE html>
<html>
  <head> 
    <link rel="stylesheet" type="text/css" href="/css/login.css" />
  </head>
  
  <body>
    <div id="wrapper"  style="position:relative">
      <div id="banner">
	<h1 style="font-family:'Open Sans',courier new;font-size:38px;font-weight:300;color:rgb(85,85,85);direction:ltr;">
	  One account. None of Google. </br>
	</h1>
	
	<h2 style="font-family:'Open Sans',courier new;font-size:18px;font-weight:400;color:rgb(85,85,85);direction:ltr;">
	  Sign in with your !Google Drive Account.
	</h2>
      </div>
      
      <div id="login-container">
	
	<div id="login">
	
	  <form id="login_form" action="/cgi-bin/handle.pl?process=login" method="post">
	    <input id="uname" autocomplete="off" type="text" value="" placeholder="Name" name="uname"/>
	    <input id="pword" type="password" value="" placeholder="Password" name="pword"/>
	    <input id="submit" type="submit" value="Sign In" name="signIn"/>
            <input id="signup" type="checkbox" value="signup" name="signup"><span id="s_text">Sign Up</span>
	  </form>
QED
    my $pass_err = $cgi->param('pass');
    my $user_err = $cgi->param('user');
    
    if(defined $pass_err || defined $user_err)  {
	print '<div id="error" style="color:red;font-size:14px;">';
	(defined $user_err && $user_err == '0' ) ? print "Enter your name.<br>" : print "";
	(defined $pass_err && $pass_err == '0' ) ? print "Enter your password.<br>" : print "";
	(defined $pass_err && $pass_err == '1' ) ? print "Incorrect password.<br>" : print "";
	print '</div>';
    }


print <<'block'	  
	</div>
      </div>
    </div>
block
